version: "3"
services:
  sendtome:
    image:  annona/sendtome:latest
    container_name: sendtome
    restart: always
    #build: .
    volumes:
      - ./.env:/app/.env
    environment:
      #- TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_GIN_RUNMODE=${SERVER_GIN_RUNMODE}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_URL=${SERVER_URL}
      - BOT_MANAGER_ID=${BOT_MANAGER_ID}
      - BOT_TELEGRAM_TOKEN=${BOT_TELEGRAM_TOKEN}
      - BOT_TELEGRAM_WEBHOOK_URL=${BOT_TELEGRAM_WEBHOOK_URL}
      - BOT_TELEGRAM_API_PROXY_URL=${BOT_TELEGRAM_API_PROXY_URL}
      - BOT_REPORT_CHAT_ID=${BOT_REPORT_CHAT_ID}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
